include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/building/maven/microservice.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/scanning/dependency-scanning.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging-docker/docker-build.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/docker-deploy.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-service/custom-image.yml'

stages:
  - build
  - test
  - pre-package
  - package
  - post-package
  - deploy

.docker-build:
  variables:
    DBLD_PARENT_IMAGE_NAME: ${REDMIC_SERVER_IMAGE_NAME}
    DBLD_PARENT_IMAGE_TAG: ${REDMIC_SERVER_IMAGE_TAG}

.deploy:
  variables:
    STACK: notification-manager
