services:
  notification-manager:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/server/notification-manager}:${IMAGE_TAG:-latest}
    environment:
      MICROSERVICE_NAME:
      MICROSERVICE_PORT:
      SPRING_MAIL_HOST:
      SPRING_MAIL_USERNAME:
      SPRING_MAIL_PASSWORD:
      SLACK_WEBHOOK_URL:
      SLACK_WEBHOOK_USERNAME:
      SLACK_WEBHOOK_CHANNEL:
      JAVA_OPTS:
    networks:
      metric-net:
      kafka-net:
    healthcheck:
      test: wget --spider -q http://localhost:${MICROSERVICE_PORT}/api/notification/actuator/health
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-5}
      start_period: ${HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-1m}
      update_config:
        delay: ${UPDATE_DELAY:-2m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-410M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true
