version: '3.5'

services:
  notification-manager:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - MICROSERVICE_NAME
      - MICROSERVICE_PORT
      - SPRING_PROFILES_ACTIVE
      - SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    networks:
      - traefik-net
      - kafka-net
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${MICROSERVICE_PORT}/api/${MICROSERVICE_NAME}/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  traefik-net:
    external: true

  kafka-net:
    external: true
