version: '3.5'

services:
  notification-manager:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - MICROSERVICE_NAME
      - MICROSERVICE_PORT
      - SPRING_PROFILES_ACTIVE
      - SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD
      - SLACK_WEBHOOK_URL
      - SLACK_WEBHOOK_USERNAME
      - SLACK_WEBHOOK_CHANNEL
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    networks:
      - traefik-net
      - kafka-net
    healthcheck:
      test: wget --spider -q http://localhost:${MICROSERVICE_PORT}/api/notification/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:${PUBLIC_HOSTNAME};PathPrefix:/api/${MICROSERVICE_NAME}
        traefik.backend: ${MICROSERVICE_NAME}
        traefik.port: "${MICROSERVICE_PORT}"
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 410M

networks:
  traefik-net:
    external: true

  kafka-net:
    external: true
